# Generated by Django 5.1.7 on 2025-06-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
